-- MySQL Script generated by MySQL Workbench
-- Sun Aug  6 00:34:39 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

-- -----------------------------------------------------
-- Schema analyses
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `analyses` ;

-- -----------------------------------------------------
-- Schema analyses
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `analyses` DEFAULT CHARACTER SET utf8 ;
USE `analyses` ;

-- --------------------------------------------------------

-- -----------------------------------------------------
-- Table `analyses`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `analyses`.`users` ;

CREATE TABLE IF NOT EXISTS `analyses`.`users` (
  `id` INT(10) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `email` VARCHAR(191) NOT NULL,
  `password` VARCHAR(191) NOT NULL,
  `type` TINYINT(4) NULL,
  `remember_token` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NULL,
  `update_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`)
  UNIQUE KEY `users_email_unique` (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `analyses`.`procedures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `analyses`.`procedures` ;

CREATE TABLE IF NOT EXISTS `analyses`.`procedures` (
  `id` INT(10) NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `create_at` TIMESTAMP NULL,
  `update_at` TIMESTAMP NULL,
  `users_id` INT(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_procedures_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_procedures_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `analyses`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `analyses`.`tests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `analyses`.`tests` ;

CREATE TABLE IF NOT EXISTS `analyses`.`tests` (
  `id` INT NULL,
  `date` DATE NOT NULL,
  `create_at` TIMESTAMP NULL,
  `update_at` TIMESTAMP NULL,
  `procedures_id` INT(10) NOT NULL,
  `users_id` INT(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tests_procedures_idx` (`procedures_id` ASC),
  INDEX `fk_tests_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_tests_procedures`
    FOREIGN KEY (`procedures_id`)
    REFERENCES `analyses`.`procedures` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tests_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `analyses`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
